#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB140719134845")]
public partial class mstDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertBEYKOZDOGA_Banner(BEYKOZDOGA_Banner instance);
  partial void UpdateBEYKOZDOGA_Banner(BEYKOZDOGA_Banner instance);
  partial void DeleteBEYKOZDOGA_Banner(BEYKOZDOGA_Banner instance);
  partial void InsertBEYKOZDOGA_Seo(BEYKOZDOGA_Seo instance);
  partial void UpdateBEYKOZDOGA_Seo(BEYKOZDOGA_Seo instance);
  partial void DeleteBEYKOZDOGA_Seo(BEYKOZDOGA_Seo instance);
  partial void InsertBEYKOZDOGA_GenelAyarlar(BEYKOZDOGA_GenelAyarlar instance);
  partial void UpdateBEYKOZDOGA_GenelAyarlar(BEYKOZDOGA_GenelAyarlar instance);
  partial void DeleteBEYKOZDOGA_GenelAyarlar(BEYKOZDOGA_GenelAyarlar instance);
  partial void InsertBEYKOZDOGA_Giri(BEYKOZDOGA_Giri instance);
  partial void UpdateBEYKOZDOGA_Giri(BEYKOZDOGA_Giri instance);
  partial void DeleteBEYKOZDOGA_Giri(BEYKOZDOGA_Giri instance);
  partial void InsertBEYKOZDOGA_Icerik(BEYKOZDOGA_Icerik instance);
  partial void UpdateBEYKOZDOGA_Icerik(BEYKOZDOGA_Icerik instance);
  partial void DeleteBEYKOZDOGA_Icerik(BEYKOZDOGA_Icerik instance);
  partial void InsertBEYKOZDOGA_OzelDurum(BEYKOZDOGA_OzelDurum instance);
  partial void UpdateBEYKOZDOGA_OzelDurum(BEYKOZDOGA_OzelDurum instance);
  partial void DeleteBEYKOZDOGA_OzelDurum(BEYKOZDOGA_OzelDurum instance);
  partial void InsertBEYKOZDOGA_Kategoriler(BEYKOZDOGA_Kategoriler instance);
  partial void UpdateBEYKOZDOGA_Kategoriler(BEYKOZDOGA_Kategoriler instance);
  partial void DeleteBEYKOZDOGA_Kategoriler(BEYKOZDOGA_Kategoriler instance);
  #endregion
	
	public mstDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB140719134845ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public mstDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public mstDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public mstDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public mstDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<BEYKOZDOGA_Banner> BEYKOZDOGA_Banners
	{
		get
		{
			return this.GetTable<BEYKOZDOGA_Banner>();
		}
	}
	
	public System.Data.Linq.Table<BEYKOZDOGA_Seo> BEYKOZDOGA_Seos
	{
		get
		{
			return this.GetTable<BEYKOZDOGA_Seo>();
		}
	}
	
	public System.Data.Linq.Table<BEYKOZDOGA_GenelAyarlar> BEYKOZDOGA_GenelAyarlars
	{
		get
		{
			return this.GetTable<BEYKOZDOGA_GenelAyarlar>();
		}
	}
	
	public System.Data.Linq.Table<BEYKOZDOGA_Giri> BEYKOZDOGA_Giris
	{
		get
		{
			return this.GetTable<BEYKOZDOGA_Giri>();
		}
	}
	
	public System.Data.Linq.Table<BEYKOZDOGA_Icerik> BEYKOZDOGA_Iceriks
	{
		get
		{
			return this.GetTable<BEYKOZDOGA_Icerik>();
		}
	}
	
	public System.Data.Linq.Table<BEYKOZDOGA_OzelDurum> BEYKOZDOGA_OzelDurums
	{
		get
		{
			return this.GetTable<BEYKOZDOGA_OzelDurum>();
		}
	}
	
	public System.Data.Linq.Table<BEYKOZDOGA_Kategoriler> BEYKOZDOGA_Kategorilers
	{
		get
		{
			return this.GetTable<BEYKOZDOGA_Kategoriler>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BEYKOZDOGA_Banner")]
public partial class BEYKOZDOGA_Banner : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Baslik;
	
	private string _AltBaslik;
	
	private string _Resim;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnBaslikChanging(string value);
    partial void OnBaslikChanged();
    partial void OnAltBaslikChanging(string value);
    partial void OnAltBaslikChanged();
    partial void OnResimChanging(string value);
    partial void OnResimChanged();
    #endregion
	
	public BEYKOZDOGA_Banner()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Baslik", DbType="NVarChar(50)")]
	public string Baslik
	{
		get
		{
			return this._Baslik;
		}
		set
		{
			if ((this._Baslik != value))
			{
				this.OnBaslikChanging(value);
				this.SendPropertyChanging();
				this._Baslik = value;
				this.SendPropertyChanged("Baslik");
				this.OnBaslikChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AltBaslik", DbType="NVarChar(50)")]
	public string AltBaslik
	{
		get
		{
			return this._AltBaslik;
		}
		set
		{
			if ((this._AltBaslik != value))
			{
				this.OnAltBaslikChanging(value);
				this.SendPropertyChanging();
				this._AltBaslik = value;
				this.SendPropertyChanged("AltBaslik");
				this.OnAltBaslikChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resim", DbType="NVarChar(50)")]
	public string Resim
	{
		get
		{
			return this._Resim;
		}
		set
		{
			if ((this._Resim != value))
			{
				this.OnResimChanging(value);
				this.SendPropertyChanging();
				this._Resim = value;
				this.SendPropertyChanged("Resim");
				this.OnResimChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BEYKOZDOGA_Seo")]
public partial class BEYKOZDOGA_Seo : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Title;
	
	private string _Description;
	
	private string _Keywords;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnKeywordsChanging(string value);
    partial void OnKeywordsChanged();
    #endregion
	
	public BEYKOZDOGA_Seo()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(MAX)")]
	public string Title
	{
		get
		{
			return this._Title;
		}
		set
		{
			if ((this._Title != value))
			{
				this.OnTitleChanging(value);
				this.SendPropertyChanging();
				this._Title = value;
				this.SendPropertyChanged("Title");
				this.OnTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keywords", DbType="NVarChar(MAX)")]
	public string Keywords
	{
		get
		{
			return this._Keywords;
		}
		set
		{
			if ((this._Keywords != value))
			{
				this.OnKeywordsChanging(value);
				this.SendPropertyChanging();
				this._Keywords = value;
				this.SendPropertyChanged("Keywords");
				this.OnKeywordsChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BEYKOZDOGA_GenelAyarlar")]
public partial class BEYKOZDOGA_GenelAyarlar : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _FirmaAdi;
	
	private string _Yetkili;
	
	private string _Telefon;
	
	private string _Fax;
	
	private string _Email;
	
	private string _Adres;
	
	private string _Harita;
	
	private string _EmailSifre;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFirmaAdiChanging(string value);
    partial void OnFirmaAdiChanged();
    partial void OnYetkiliChanging(string value);
    partial void OnYetkiliChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    partial void OnHaritaChanging(string value);
    partial void OnHaritaChanged();
    partial void OnEmailSifreChanging(string value);
    partial void OnEmailSifreChanged();
    #endregion
	
	public BEYKOZDOGA_GenelAyarlar()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirmaAdi", DbType="NVarChar(50)")]
	public string FirmaAdi
	{
		get
		{
			return this._FirmaAdi;
		}
		set
		{
			if ((this._FirmaAdi != value))
			{
				this.OnFirmaAdiChanging(value);
				this.SendPropertyChanging();
				this._FirmaAdi = value;
				this.SendPropertyChanged("FirmaAdi");
				this.OnFirmaAdiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yetkili", DbType="NVarChar(50)")]
	public string Yetkili
	{
		get
		{
			return this._Yetkili;
		}
		set
		{
			if ((this._Yetkili != value))
			{
				this.OnYetkiliChanging(value);
				this.SendPropertyChanging();
				this._Yetkili = value;
				this.SendPropertyChanged("Yetkili");
				this.OnYetkiliChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="NVarChar(50)")]
	public string Telefon
	{
		get
		{
			return this._Telefon;
		}
		set
		{
			if ((this._Telefon != value))
			{
				this.OnTelefonChanging(value);
				this.SendPropertyChanging();
				this._Telefon = value;
				this.SendPropertyChanged("Telefon");
				this.OnTelefonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="NVarChar(50)")]
	public string Fax
	{
		get
		{
			return this._Fax;
		}
		set
		{
			if ((this._Fax != value))
			{
				this.OnFaxChanging(value);
				this.SendPropertyChanging();
				this._Fax = value;
				this.SendPropertyChanged("Fax");
				this.OnFaxChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="NVarChar(250)")]
	public string Adres
	{
		get
		{
			return this._Adres;
		}
		set
		{
			if ((this._Adres != value))
			{
				this.OnAdresChanging(value);
				this.SendPropertyChanging();
				this._Adres = value;
				this.SendPropertyChanged("Adres");
				this.OnAdresChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Harita", DbType="NVarChar(MAX)")]
	public string Harita
	{
		get
		{
			return this._Harita;
		}
		set
		{
			if ((this._Harita != value))
			{
				this.OnHaritaChanging(value);
				this.SendPropertyChanging();
				this._Harita = value;
				this.SendPropertyChanged("Harita");
				this.OnHaritaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailSifre", DbType="NVarChar(50)")]
	public string EmailSifre
	{
		get
		{
			return this._EmailSifre;
		}
		set
		{
			if ((this._EmailSifre != value))
			{
				this.OnEmailSifreChanging(value);
				this.SendPropertyChanging();
				this._EmailSifre = value;
				this.SendPropertyChanged("EmailSifre");
				this.OnEmailSifreChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BEYKOZDOGA_Giris")]
public partial class BEYKOZDOGA_Giri : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _KullaniciAdi;
	
	private string _Sifre;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKullaniciAdiChanging(string value);
    partial void OnKullaniciAdiChanged();
    partial void OnSifreChanging(string value);
    partial void OnSifreChanged();
    #endregion
	
	public BEYKOZDOGA_Giri()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullaniciAdi", DbType="NVarChar(50)")]
	public string KullaniciAdi
	{
		get
		{
			return this._KullaniciAdi;
		}
		set
		{
			if ((this._KullaniciAdi != value))
			{
				this.OnKullaniciAdiChanging(value);
				this.SendPropertyChanging();
				this._KullaniciAdi = value;
				this.SendPropertyChanged("KullaniciAdi");
				this.OnKullaniciAdiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sifre", DbType="NVarChar(50)")]
	public string Sifre
	{
		get
		{
			return this._Sifre;
		}
		set
		{
			if ((this._Sifre != value))
			{
				this.OnSifreChanging(value);
				this.SendPropertyChanging();
				this._Sifre = value;
				this.SendPropertyChanged("Sifre");
				this.OnSifreChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BEYKOZDOGA_Icerik")]
public partial class BEYKOZDOGA_Icerik : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Baslik;
	
	private string _Resim;
	
	private string _Detay;
	
	private System.Nullable<int> _KatID;
	
	private string _Yol;
	
	private string _KucukResim;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnBaslikChanging(string value);
    partial void OnBaslikChanged();
    partial void OnResimChanging(string value);
    partial void OnResimChanged();
    partial void OnDetayChanging(string value);
    partial void OnDetayChanged();
    partial void OnKatIDChanging(System.Nullable<int> value);
    partial void OnKatIDChanged();
    partial void OnYolChanging(string value);
    partial void OnYolChanged();
    partial void OnKucukResimChanging(string value);
    partial void OnKucukResimChanged();
    #endregion
	
	public BEYKOZDOGA_Icerik()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Baslik", DbType="NVarChar(50)")]
	public string Baslik
	{
		get
		{
			return this._Baslik;
		}
		set
		{
			if ((this._Baslik != value))
			{
				this.OnBaslikChanging(value);
				this.SendPropertyChanging();
				this._Baslik = value;
				this.SendPropertyChanged("Baslik");
				this.OnBaslikChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resim", DbType="NVarChar(50)")]
	public string Resim
	{
		get
		{
			return this._Resim;
		}
		set
		{
			if ((this._Resim != value))
			{
				this.OnResimChanging(value);
				this.SendPropertyChanging();
				this._Resim = value;
				this.SendPropertyChanged("Resim");
				this.OnResimChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detay", DbType="NVarChar(MAX)")]
	public string Detay
	{
		get
		{
			return this._Detay;
		}
		set
		{
			if ((this._Detay != value))
			{
				this.OnDetayChanging(value);
				this.SendPropertyChanging();
				this._Detay = value;
				this.SendPropertyChanged("Detay");
				this.OnDetayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KatID", DbType="Int")]
	public System.Nullable<int> KatID
	{
		get
		{
			return this._KatID;
		}
		set
		{
			if ((this._KatID != value))
			{
				this.OnKatIDChanging(value);
				this.SendPropertyChanging();
				this._KatID = value;
				this.SendPropertyChanged("KatID");
				this.OnKatIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yol", DbType="NVarChar(50)")]
	public string Yol
	{
		get
		{
			return this._Yol;
		}
		set
		{
			if ((this._Yol != value))
			{
				this.OnYolChanging(value);
				this.SendPropertyChanging();
				this._Yol = value;
				this.SendPropertyChanged("Yol");
				this.OnYolChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KucukResim", DbType="NVarChar(50)")]
	public string KucukResim
	{
		get
		{
			return this._KucukResim;
		}
		set
		{
			if ((this._KucukResim != value))
			{
				this.OnKucukResimChanging(value);
				this.SendPropertyChanging();
				this._KucukResim = value;
				this.SendPropertyChanged("KucukResim");
				this.OnKucukResimChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BEYKOZDOGA_OzelDurum")]
public partial class BEYKOZDOGA_OzelDurum : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Baslik;
	
	private string _KucukResim;
	
	private string _Resim;
	
	private string _Yol;
	
	private string _KisaYazi;
	
	private string _Detay;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnBaslikChanging(string value);
    partial void OnBaslikChanged();
    partial void OnKucukResimChanging(string value);
    partial void OnKucukResimChanged();
    partial void OnResimChanging(string value);
    partial void OnResimChanged();
    partial void OnYolChanging(string value);
    partial void OnYolChanged();
    partial void OnKisaYaziChanging(string value);
    partial void OnKisaYaziChanged();
    partial void OnDetayChanging(string value);
    partial void OnDetayChanged();
    #endregion
	
	public BEYKOZDOGA_OzelDurum()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Baslik", DbType="NVarChar(50)")]
	public string Baslik
	{
		get
		{
			return this._Baslik;
		}
		set
		{
			if ((this._Baslik != value))
			{
				this.OnBaslikChanging(value);
				this.SendPropertyChanging();
				this._Baslik = value;
				this.SendPropertyChanged("Baslik");
				this.OnBaslikChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KucukResim", DbType="NVarChar(50)")]
	public string KucukResim
	{
		get
		{
			return this._KucukResim;
		}
		set
		{
			if ((this._KucukResim != value))
			{
				this.OnKucukResimChanging(value);
				this.SendPropertyChanging();
				this._KucukResim = value;
				this.SendPropertyChanged("KucukResim");
				this.OnKucukResimChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resim", DbType="NVarChar(50)")]
	public string Resim
	{
		get
		{
			return this._Resim;
		}
		set
		{
			if ((this._Resim != value))
			{
				this.OnResimChanging(value);
				this.SendPropertyChanging();
				this._Resim = value;
				this.SendPropertyChanged("Resim");
				this.OnResimChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yol", DbType="NVarChar(50)")]
	public string Yol
	{
		get
		{
			return this._Yol;
		}
		set
		{
			if ((this._Yol != value))
			{
				this.OnYolChanging(value);
				this.SendPropertyChanging();
				this._Yol = value;
				this.SendPropertyChanged("Yol");
				this.OnYolChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KisaYazi", DbType="NVarChar(200)")]
	public string KisaYazi
	{
		get
		{
			return this._KisaYazi;
		}
		set
		{
			if ((this._KisaYazi != value))
			{
				this.OnKisaYaziChanging(value);
				this.SendPropertyChanging();
				this._KisaYazi = value;
				this.SendPropertyChanged("KisaYazi");
				this.OnKisaYaziChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detay", DbType="NVarChar(MAX)")]
	public string Detay
	{
		get
		{
			return this._Detay;
		}
		set
		{
			if ((this._Detay != value))
			{
				this.OnDetayChanging(value);
				this.SendPropertyChanging();
				this._Detay = value;
				this.SendPropertyChanged("Detay");
				this.OnDetayChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BEYKOZDOGA_Kategoriler")]
public partial class BEYKOZDOGA_Kategoriler : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _KategoriAdi;
	
	private string _UstID;
	
	private string _UstKategoriAdi;
	
	private string _Durum;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKategoriAdiChanging(string value);
    partial void OnKategoriAdiChanged();
    partial void OnUstIDChanging(string value);
    partial void OnUstIDChanged();
    partial void OnUstKategoriAdiChanging(string value);
    partial void OnUstKategoriAdiChanged();
    partial void OnDurumChanging(string value);
    partial void OnDurumChanged();
    #endregion
	
	public BEYKOZDOGA_Kategoriler()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KategoriAdi", DbType="NVarChar(50)")]
	public string KategoriAdi
	{
		get
		{
			return this._KategoriAdi;
		}
		set
		{
			if ((this._KategoriAdi != value))
			{
				this.OnKategoriAdiChanging(value);
				this.SendPropertyChanging();
				this._KategoriAdi = value;
				this.SendPropertyChanged("KategoriAdi");
				this.OnKategoriAdiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UstID", DbType="NVarChar(20)")]
	public string UstID
	{
		get
		{
			return this._UstID;
		}
		set
		{
			if ((this._UstID != value))
			{
				this.OnUstIDChanging(value);
				this.SendPropertyChanging();
				this._UstID = value;
				this.SendPropertyChanged("UstID");
				this.OnUstIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UstKategoriAdi", DbType="NVarChar(50)")]
	public string UstKategoriAdi
	{
		get
		{
			return this._UstKategoriAdi;
		}
		set
		{
			if ((this._UstKategoriAdi != value))
			{
				this.OnUstKategoriAdiChanging(value);
				this.SendPropertyChanging();
				this._UstKategoriAdi = value;
				this.SendPropertyChanged("UstKategoriAdi");
				this.OnUstKategoriAdiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Durum", DbType="NVarChar(50)")]
	public string Durum
	{
		get
		{
			return this._Durum;
		}
		set
		{
			if ((this._Durum != value))
			{
				this.OnDurumChanging(value);
				this.SendPropertyChanging();
				this._Durum = value;
				this.SendPropertyChanged("Durum");
				this.OnDurumChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
